version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp-test
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: example
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: example
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-cli.phar:/usr/local/bin/wp # Dodanie WP-CLI

  db:
    image: mysql:5.7
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
