version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp-test
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_test
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
