name: CI/CD WordPress Test Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start WordPress containers
        run: docker-compose up -d

      - name: Run PHPUnit tests
        run: |
          docker exec -it wp-test wp plugin install --activate
          docker exec -it wp-test ./vendor/bin/phpunit
